### ISSUE TITLE
Problem with ~ characted

### ISSUE THREAD

**Issue by mirzadelic** [mozilla/unicode-slugify#15]
`~` character is making problem with slugify..

**Comment by eminbugrasaral** [comment]
You can pass it with "ok" parameter to discard it.

**Comment by mirzadelic** [comment]
Thanks..

**Comment by eminbugrasaral** [comment]
By default, slug_ok characters are: -, _, ~ in a format of '-_~'. So, what you wanna do: slugify(my_string, '-_')
Regards.
