### ISSUE TITLE
'ascii' codec can't decode byte 0xc3 in position 361 at open('README.md').read(),

### ISSUE THREAD

**Issue by dz0ny** [mozilla/unicode-slugify#16]
```
  Downloading unicode-slugify-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-s4ot22tg/unicode-slugify/setup.py", line 7, in <module>
        long_description=open('README.md').read(),
      File "/var/cache/drone/src/github.com/dz0ny/app/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 361: ordinal not in range(128)
```

**Comment by dz0ny** [comment]
missing read().encode('utf-8') > convert to bytes :)

**Comment by pahaz** [comment]
same issues

    ==> default: Collecting unicode-slugify==0.1.3 (from -r requirements.txt (line 6))
    ==> default:   Downloading unicode-slugify-0.1.3.tar.gz
    ==> default:     Complete output from command python setup.py egg_info:
    ==> default:     Traceback (most recent call last):
    ==> default:       File "<string>", line 20, in <module>
    ==> default:       File "/tmp/pip-build-v2uel0_x/unicode-slugify/setup.py", line 7, in <module>
    ==> default:         long_description=open('README.md').read(),
    ==> default:       File "/DATA/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
    ==> default:         return codecs.ascii_decode(input, self.errors)[0]
    ==> default:     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 361: ordinal not in range(128)
    ==> default:
    ==> default:     ----------------------------------------
    ==> default: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v2uel0_x/unicode-slugify
    The SSH command responded with a non-zero exit status. Vagrant
    assumes that this means the command failed. The output for this command
    should be in the log above. Please read the output to determine what
    went wrong.

**Comment by kirsle** [comment]
This issue was fixed once before in PR #9 and then reverted in https://github.com/mozilla/unicode-slugify/commit/02c20066e4af8fc5c929a19301f0d8e4bbba629b

A work-around I found is to set the system locale to UTF-8. For example, when using Docker with the Ubuntu base image, the locale is not set by default and this error comes up when trying to install this module. Add these commands to the Dockerfile to work around this (found [here](http://askubuntu.com/questions/581458/how-to-configure-locales-to-unicode-in-a-docker-ubuntu-14-04-container)):

```Dockerfile
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
```

Or, if not using Docker just run the commands at the shell (and look into how to set them permanently so they persist on reboot, e.g. [Ubuntu Locale](https://help.ubuntu.com/community/Locale)):

```bash
root# locale-gen en_US.UTF-8
root# export LANG en_US.UTF-8
root# export LANGUAGE en_US:en
```

**Comment by grimlaufer** [comment]
I had the same error, changing line 7 in setup.py to 
```long_description=open('README.md', 'r', encoding='utf-8').read() ``` fixed it for me.

**Comment by vigneshsarma** [comment]
Can I give a pull request with @grimlaufer's solution? I am also facing this issue.

**Comment by marceltschoppch** [comment]
I just added a pull request with the solution from @grimlaufer, slightly adjusted to not break environments with python < 3.0

**Comment by jerkyrs** [comment]
Sorry i know this is old thread but if you are using Docker container assuming you are doing something like this

```
RUN yum -y update
RUN yum -y install epel-release
RUN yum -y install centos-release-scl centos-release-scl-rh
RUN yum -y install git
RUN yum -y install python36 rh-python36-python rh-python36-python-pip rh-python36-python-virtualenv
```

Make sure you add your ENV after the above
```
RUN localedef -i en_US -f UTF-8 C.UTF-8 
ENV LANG="C.UTF-8"
ENV LC_LANG="C.UTF-8"
```
