### ISSUE TITLE
"pip install unicode-slugify" is missing files

### ISSUE THREAD

**Issue by tirithen** [mozilla/unicode-slugify#3]
I cannot install this package with pip, the following happens

$ sudo pip install unicode-slugify
Downloading/unpacking unicode-slugify
  Could not find any downloads that satisfy the requirement unicode-slugify
No distributions at all found for unicode-slugify
Storing complete log in /home/tirithen/.pip/pip.log

And the log says:

------------------------------------------------------------
/usr/bin/pip run on Wed Jan 25 13:58:45 2012
Downloading/unpacking unicode-slugify
  Getting page http://pypi.python.org/simple/unicode-slugify
  URLs to search for versions for unicode-slugify:
  * http://pypi.python.org/simple/unicode-slugify/
  Getting page http://github.com/mozilla/unicode-slugify
  Analyzing links from page http://pypi.python.org/simple/unicode-slugify/
    Skipping link http://github.com/mozilla/unicode-slugify (from http://pypi.python.org/simple/unicode-slugify/); not a file
  Analyzing links from page https://github.com/mozilla/unicode-slugify
    Skipping link https://github.com/opensearch.xml (from https://github.com/mozilla/unicode-slugify); unknown archive format: .xml
    Skipping link https://github.com/fluidicon.png (from https://github.com/mozilla/unicode-slugify); unknown archive format: .png
    Skipping link https://a248.e.akamai.net/assets.github.com/stylesheets/bundles/github-31ce35e65492efdddc8289c3acbc0cfc685612dc.css (from https://github.com/mozilla/unicode-slugify); unknown archive format: .css
    Skipping link https://github.com/mozilla/unicode-slugify/tree/4431bee634b19b8f2849c62c81fffa08375abfad (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/commits/master.atom (from https://github.com/mozilla/unicode-slugify); unknown archive format: .atom
    Skipping link https://github.com (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/plans (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/explore (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/features (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/blog (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/login?return_to=%2Fmozilla%2Funicode-slugify (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/watchers (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/network (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/pulls (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/issues (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/graphs (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify#readme (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http:// (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/zipball/master (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify.git (from https://github.com/mozilla/unicode-slugify); unknown archive format: .git
    Skipping link git://github.com/mozilla/unicode-slugify.git (from https://github.com/mozilla/unicode-slugify); unknown archive format: .git
    Skipping link https://github.com/mozilla/unicode-slugify/dismiss-tree-finder-help (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link javascript:; (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/tree/master (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/commits/master (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/branches (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/tags (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/downloads (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/commit/4431bee634b19b8f2849c62c81fffa08375abfad (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/issues/2 (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/davedash (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/commits/master/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/tree/4431bee634b19b8f2849c62c81fffa08375abfad/slugify (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/commit/0303c4b824bc7ee8b692a6ccc22037daee02b207 (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/brodie (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/blob/4431bee634b19b8f2849c62c81fffa08375abfad/.gitignore (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/commit/a082e5e847bf3e7a362a5e8cf1372251defe9935 (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/blob/4431bee634b19b8f2849c62c81fffa08375abfad/LICENSE (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/blob/4431bee634b19b8f2849c62c81fffa08375abfad/MANIFEST.in (from https://github.com/mozilla/unicode-slugify); unknown archive format: .in
    Skipping link https://github.com/mozilla/unicode-slugify/commit/f0fada39c86e61ad82b83604ba25d4fc16ee3f84 (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/mozilla/unicode-slugify/blob/4431bee634b19b8f2849c62c81fffa08375abfad/README.md (from https://github.com/mozilla/unicode-slugify); unknown archive format: .md
    Skipping link https://github.com/mozilla/unicode-slugify/blob/4431bee634b19b8f2849c62c81fffa08375abfad/requirements.txt (from https://github.com/mozilla/unicode-slugify); unknown archive format: .txt
    Skipping link https://github.com/mozilla/unicode-slugify/blob/4431bee634b19b8f2849c62c81fffa08375abfad/setup.py (from https://github.com/mozilla/unicode-slugify); unknown archive format: .py
    Skipping link https://github.com/mozilla/unicode-slugify/commit/5b2f6dd8c3e6bfa61cd2843c3f90962e38fc9b0d (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/about (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/contact (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/training (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://enterprise.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://status.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://get.gaug.es/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://speakerdeck.com (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://gist.github.com (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://mac.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://mobile.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://jobs.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://shop.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://octodex.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://help.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://developer.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://github.github.com/github-flavored-markdown/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://pages.github.com/ (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/site/terms (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/site/privacy (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link https://github.com/security (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://www.rackspace.com (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://www.rackspace.com%20 (from https://github.com/mozilla/unicode-slugify); not a file
    Skipping link http://www.rackspacecloud.com (from https://github.com/mozilla/unicode-slugify); not a file
  Could not find any downloads that satisfy the requirement unicode-slugify
No distributions at all found for unicode-slugify
Exception information:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/pip/basecommand.py", line 130, in main
    self.run(options, args)
  File "/usr/lib/pymodules/python2.7/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/pymodules/python2.7/pip/req.py", line 911, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/pymodules/python2.7/pip/index.py", line 154, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for unicode-slugify

**Comment by eminbugrasaral** [comment]
Please consider updating the package to 0.1.3. Thanks.

**Comment by davedash** [comment]
Sorry folks, I haven't used this project for a few years so I let these issues slipped. It's definitely fixed in 2015 ;)
